apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo
  name: demo-deployment
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 4000
    protocol: TCP
  selector:
    app: demo
  type: LoadBalancer # this is a loadbalancer so it can be viewed on the internet. 
                     # Not usually required if you have an external load balancer set up through an ingress controller
