apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: angelakinder/elixir-phoenix:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: MIX_ENV
          valueFrom: 
            configMapKeyRef:
              key:  mix-env
              name: demo
        - name: APP_NAME
          valueFrom: 
            configMapKeyRef:
              key:  app-name
              name: demo
        - name: PORT
          valueFrom: 
            configMapKeyRef:
              key:  port
              name: demo
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: postgres-db
              name: demo
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: postgres-password
              name: demo
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: postgres-user
              name: demo
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              key: postgres-host
              name: demo    
