apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres # Label selector that determines which Pods belong to the StatefulSet
                 # Must match spec: template: metadata: labels
  serviceName: "postgres"
  replicas: 3
  template:
    metadata:
      labels:
        app: postgres # Pod template's label selector
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:10.4
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/db-data
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: postgres-db
              name: demo
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: postgres-password
              name: demo
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: postgres-user
              name: demo
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi