apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 5432
    name: tcp
  type: LoadBalancer # this is a loadbalancer so it can be viewed on the internet. 
  selector:
    app: postgres